# Generated by Django 5.1.4 on 2025-02-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='emprunteur',
            new_name='membre',
        ),
    ]
