# Generated by Django 5.1.4 on 2025-02-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_emprunt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='date_retour',
            new_name='date_retour_prevu',
        ),
    ]
