# Generated by Django 5.1.4 on 2025-02-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_alter_emprunt_date_retour_prevu'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
