# Generated by Django 5.1.4 on 2025-02-06 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0006_emprunt_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour_prevu',
            field=models.DateField(default=datetime.date(2025, 2, 13)),
        ),
    ]
