# Generated by Django 5.1.4 on 2025-01-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jeu_de_plateau',
            new_name='Jeu',
        ),
    ]
