# Generated by Django 5.1.4 on 2025-02-04 08:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_rename_emprunteur_media_membre'),
        ('mediatheque', '0002_rename_jeu_de_plateau_jeu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(default=datetime.date(2025, 2, 11))),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.media')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.membre')),
            ],
        ),
    ]
