# Generated by Django 5.1.4 on 2025-02-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0003_emprunt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprunt',
        ),
    ]
